version: '3'
services:
  scrapyd:
    build:
      context: .
      dockerfile: scrapyd/Dockerfile
    ports:
      - "6800:6800"
    depends_on:
      - db
      - redis
    env_file: 
      - ./scrapyd.env
    container_name: "autoproxy_scrapyd"
  redis-overcommit:
    build: https://github.com/bkuhl/redis-overcommit-on-host.git
    restart: 'no'
    privileged: true
    volumes:
      - /proc/sys/vm:/mnt/vm
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass somepassword
    ports:
      - "5379:6379"
    container_name: "autoproxy_redis"
    depends_on:
      - redis-overcommit
  db:
#   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres"
#   Give the container the name my_postgres. You can changes to something else.
    container_name: "autoproxy_db"
#   Setup the username, password, and database name. You can changes these values.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=somepassword
      - POSTGRES_DB=proxies
#   Maps port 54320 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "54320:5432"
#   Set a volume some that database is not lost after shutting down the container.
#   I used the name postgres-data but you can changed it to something else.
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
  spider_scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    env_file: 
      - ./scrapyd.env
    depends_on:
      - scrapyd
    container_name: autoproxy_scheduler